import 'demo_catalog.dart';

/// Hardware / Sanitary demo catalog.
const hardwareSanitaryCatalog = DemoCatalog(
  categories: [
    'Plumbing',
    'Electrical',
    'Bathroom Fittings',
    'Hardware',
    'Tools',
    'Pipes & Fittings',
  ],
  products: [
    DemoProduct(
      name: 'PVC Pipe 1 inch - 3 Meter',
      code: 'HWS-PIP-001',
      category: 'Pipes & Fittings',
      purchasePrice: 120,
      sellingPrice: 175,
      mrp: 190,
      taxPercent: 18,
      unit: 'piece',
      stock: 100,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'PVC Elbow 1 inch',
      code: 'HWS-PIP-002',
      category: 'Pipes & Fittings',
      purchasePrice: 12,
      sellingPrice: 20,
      mrp: 22,
      taxPercent: 18,
      unit: 'piece',
      stock: 250,
      lowStock: 50,
    ),
    DemoProduct(
      name: 'PVC Tee 1 inch',
      code: 'HWS-PIP-003',
      category: 'Pipes & Fittings',
      purchasePrice: 15,
      sellingPrice: 25,
      mrp: 28,
      taxPercent: 18,
      unit: 'piece',
      stock: 200,
      lowStock: 40,
    ),
    DemoProduct(
      name: 'Wall Mixer',
      code: 'HWS-BTH-001',
      category: 'Bathroom Fittings',
      purchasePrice: 1450,
      sellingPrice: 2199,
      mrp: 2499,
      taxPercent: 18,
      unit: 'piece',
      stock: 25,
      lowStock: 5,
    ),
    DemoProduct(
      name: 'Health Faucet',
      code: 'HWS-BTH-002',
      category: 'Bathroom Fittings',
      purchasePrice: 280,
      sellingPrice: 449,
      mrp: 499,
      taxPercent: 18,
      unit: 'piece',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Angle Valve 1/2 inch',
      code: 'HWS-PLB-001',
      category: 'Plumbing',
      purchasePrice: 90,
      sellingPrice: 149,
      mrp: 165,
      taxPercent: 18,
      unit: 'piece',
      stock: 80,
      lowStock: 15,
    ),
    DemoProduct(
      name: 'PTFE Thread Seal Tape',
      code: 'HWS-PLB-002',
      category: 'Plumbing',
      purchasePrice: 12,
      sellingPrice: 25,
      mrp: 30,
      taxPercent: 18,
      unit: 'roll',
      stock: 150,
      lowStock: 30,
    ),
    DemoProduct(
      name: 'Modular Switch 6A',
      code: 'HWS-ELC-001',
      category: 'Electrical',
      purchasePrice: 35,
      sellingPrice: 59,
      mrp: 65,
      taxPercent: 18,
      unit: 'piece',
      stock: 120,
      lowStock: 25,
    ),
    DemoProduct(
      name: 'LED Bulb 9W',
      code: 'HWS-ELC-002',
      category: 'Electrical',
      purchasePrice: 55,
      sellingPrice: 89,
      mrp: 99,
      taxPercent: 18,
      unit: 'piece',
      stock: 100,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'Adjustable Wrench 10 inch',
      code: 'HWS-TOL-001',
      category: 'Tools',
      purchasePrice: 180,
      sellingPrice: 299,
      mrp: 340,
      taxPercent: 18,
      unit: 'piece',
      stock: 30,
      lowStock: 6,
    ),
  ],
);
