import 'demo_catalog.dart';

/// Hotel / restaurant demo catalog.
const hotelCatalog = DemoCatalog(
  categories: [
    'Breakfast',
    'Starters',
    'Main Course',
    'Rice & Biryani',
    'Breads',
    'Beverages',
    'Desserts',
  ],
  products: [
    DemoProduct(
      name: 'Masala Dosa',
      code: 'HTL-BRK-001',
      category: 'Breakfast',
      purchasePrice: 45,
      sellingPrice: 90,
      mrp: 90,
      taxPercent: 5,
      unit: 'plate',
      stock: 100,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'Idli Sambar',
      code: 'HTL-BRK-002',
      category: 'Breakfast',
      purchasePrice: 30,
      sellingPrice: 70,
      mrp: 70,
      taxPercent: 5,
      unit: 'plate',
      stock: 100,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'Paneer Tikka',
      code: 'HTL-STR-001',
      category: 'Starters',
      purchasePrice: 110,
      sellingPrice: 220,
      mrp: 220,
      taxPercent: 5,
      unit: 'plate',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Veg Manchurian',
      code: 'HTL-STR-002',
      category: 'Starters',
      purchasePrice: 90,
      sellingPrice: 180,
      mrp: 180,
      taxPercent: 5,
      unit: 'plate',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Paneer Butter Masala',
      code: 'HTL-MCR-001',
      category: 'Main Course',
      purchasePrice: 100,
      sellingPrice: 210,
      mrp: 210,
      taxPercent: 5,
      unit: 'bowl',
      stock: 60,
      lowStock: 12,
    ),
    DemoProduct(
      name: 'Dal Tadka',
      code: 'HTL-MCR-002',
      category: 'Main Course',
      purchasePrice: 55,
      sellingPrice: 120,
      mrp: 120,
      taxPercent: 5,
      unit: 'bowl',
      stock: 70,
      lowStock: 15,
    ),
    DemoProduct(
      name: 'Veg Biryani',
      code: 'HTL-RCE-001',
      category: 'Rice & Biryani',
      purchasePrice: 80,
      sellingPrice: 180,
      mrp: 180,
      taxPercent: 5,
      unit: 'plate',
      stock: 60,
      lowStock: 12,
    ),
    DemoProduct(
      name: 'Butter Naan',
      code: 'HTL-BRD-001',
      category: 'Breads',
      purchasePrice: 20,
      sellingPrice: 50,
      mrp: 50,
      taxPercent: 5,
      unit: 'piece',
      stock: 150,
      lowStock: 30,
    ),
    DemoProduct(
      name: 'Fresh Lime Soda',
      code: 'HTL-BEV-001',
      category: 'Beverages',
      purchasePrice: 25,
      sellingPrice: 70,
      mrp: 70,
      taxPercent: 5,
      unit: 'glass',
      stock: 100,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'Gulab Jamun',
      code: 'HTL-DES-001',
      category: 'Desserts',
      purchasePrice: 25,
      sellingPrice: 60,
      mrp: 60,
      taxPercent: 5,
      unit: 'plate',
      stock: 80,
      lowStock: 15,
    ),
  ],
);
