import 'demo_catalog.dart';

/// Generic demo catalog for businesses that don't fit a predefined category.
const otherCatalog = DemoCatalog(
  categories: [
    'General',
    'Household',
    'Personal Care',
    'Stationery',
    'Food & Beverages',
    'Accessories',
  ],
  products: [
    DemoProduct(
      name: 'Premium Notebook',
      code: 'OTH-STA-001',
      category: 'Stationery',
      purchasePrice: 45,
      sellingPrice: 79,
      mrp: 89,
      taxPercent: 12,
      unit: 'piece',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Ball Pen Blue',
      code: 'OTH-STA-002',
      category: 'Stationery',
      purchasePrice: 5,
      sellingPrice: 10,
      mrp: 10,
      taxPercent: 12,
      unit: 'piece',
      stock: 200,
      lowStock: 40,
    ),
    DemoProduct(
      name: 'LED Emergency Light',
      code: 'OTH-GEN-001',
      category: 'General',
      purchasePrice: 350,
      sellingPrice: 599,
      mrp: 699,
      taxPercent: 18,
      unit: 'piece',
      stock: 30,
      lowStock: 6,
    ),
    DemoProduct(
      name: 'Cleaning Liquid 1L',
      code: 'OTH-HOU-001',
      category: 'Household',
      purchasePrice: 90,
      sellingPrice: 149,
      mrp: 165,
      taxPercent: 18,
      unit: 'bottle',
      stock: 60,
      lowStock: 12,
    ),
    DemoProduct(
      name: 'Microfiber Cleaning Cloth',
      code: 'OTH-HOU-002',
      category: 'Household',
      purchasePrice: 30,
      sellingPrice: 59,
      mrp: 69,
      taxPercent: 18,
      unit: 'piece',
      stock: 100,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'Hand Wash 250ml',
      code: 'OTH-PER-001',
      category: 'Personal Care',
      purchasePrice: 55,
      sellingPrice: 99,
      mrp: 110,
      taxPercent: 18,
      unit: 'bottle',
      stock: 70,
      lowStock: 15,
    ),
    DemoProduct(
      name: 'Shampoo 180ml',
      code: 'OTH-PER-002',
      category: 'Personal Care',
      purchasePrice: 85,
      sellingPrice: 149,
      mrp: 165,
      taxPercent: 18,
      unit: 'bottle',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Bottled Water 1L',
      code: 'OTH-FNB-001',
      category: 'Food & Beverages',
      purchasePrice: 12,
      sellingPrice: 20,
      mrp: 20,
      taxPercent: 5,
      unit: 'bottle',
      stock: 200,
      lowStock: 40,
    ),
    DemoProduct(
      name: 'Mobile Charging Cable',
      code: 'OTH-ACC-001',
      category: 'Accessories',
      purchasePrice: 100,
      sellingPrice: 179,
      mrp: 199,
      taxPercent: 18,
      unit: 'piece',
      stock: 40,
      lowStock: 8,
    ),
    DemoProduct(
      name: 'Reusable Shopping Bag',
      code: 'OTH-ACC-002',
      category: 'Accessories',
      purchasePrice: 20,
      sellingPrice: 49,
      mrp: 59,
      taxPercent: 18,
      unit: 'piece',
      stock: 100,
      lowStock: 20,
    ),
  ],
);
