import 'demo_catalog.dart';

/// Rice Mill demo catalog — paddy input, finished rice, by-products, packaging.
const riceMillCatalog = DemoCatalog(
  categories: [
    'Raw Material',
    'Finished Rice',
    'By-products',
    'Packaging',
  ],
  products: [
    // ── Raw Material ────────────────────────────────────────────────────────
    DemoProduct(
      name: 'Paddy PR-106',
      code: 'RM-PAD-001',
      category: 'Raw Material',
      purchasePrice: 1800,
      sellingPrice: 1800,
      unit: 'quintal',
      stock: 500,
      lowStock: 50,
      taxPercent: 0,
    ),
    DemoProduct(
      name: 'Paddy Sona Masoori',
      code: 'RM-PAD-002',
      category: 'Raw Material',
      purchasePrice: 2100,
      sellingPrice: 2100,
      unit: 'quintal',
      stock: 300,
      lowStock: 30,
      taxPercent: 0,
    ),
    DemoProduct(
      name: 'Paddy IR-64',
      code: 'RM-PAD-003',
      category: 'Raw Material',
      purchasePrice: 1750,
      sellingPrice: 1750,
      unit: 'quintal',
      stock: 200,
      lowStock: 20,
      taxPercent: 0,
    ),

    // ── Finished Rice ───────────────────────────────────────────────────────
    DemoProduct(
      name: 'Raw Rice PR-106',
      code: 'FG-RICE-001',
      category: 'Finished Rice',
      purchasePrice: 0,
      sellingPrice: 2800,
      mrp: 2900,
      unit: 'quintal',
      stock: 0,
      lowStock: 20,
      taxPercent: 5,
    ),
    DemoProduct(
      name: 'Boiled Rice Sona Masoori',
      code: 'FG-RICE-002',
      category: 'Finished Rice',
      purchasePrice: 0,
      sellingPrice: 3200,
      mrp: 3300,
      unit: 'quintal',
      stock: 0,
      lowStock: 20,
      taxPercent: 5,
    ),
    DemoProduct(
      name: 'Broken Rice',
      code: 'FG-BKN-001',
      category: 'Finished Rice',
      purchasePrice: 0,
      sellingPrice: 1400,
      mrp: 1500,
      unit: 'quintal',
      stock: 0,
      lowStock: 10,
      taxPercent: 5,
    ),

    // ── By-products ─────────────────────────────────────────────────────────
    DemoProduct(
      name: 'Rice Bran',
      code: 'BP-BRAN-001',
      category: 'By-products',
      purchasePrice: 0,
      sellingPrice: 1200,
      mrp: 1300,
      unit: 'quintal',
      stock: 0,
      lowStock: 10,
      taxPercent: 5,
    ),
    DemoProduct(
      name: 'Husk',
      code: 'BP-HUSK-001',
      category: 'By-products',
      purchasePrice: 0,
      sellingPrice: 200,
      mrp: 250,
      unit: 'quintal',
      stock: 0,
      lowStock: 5,
      taxPercent: 0,
    ),

    // ── Packaging ────────────────────────────────────────────────────────────
    DemoProduct(
      name: 'Gunny Bag 50kg',
      code: 'PKG-GUNNY-001',
      category: 'Packaging',
      purchasePrice: 28,
      sellingPrice: 35,
      unit: 'piece',
      stock: 1000,
      lowStock: 100,
      taxPercent: 12,
    ),
    DemoProduct(
      name: 'PP Woven Bag 50kg',
      code: 'PKG-PP-001',
      category: 'Packaging',
      purchasePrice: 22,
      sellingPrice: 28,
      unit: 'piece',
      stock: 500,
      lowStock: 100,
      taxPercent: 12,
    ),
  ],
);
